### ISSUE TITLE
pandoc version 1.19 is old

### ISSUE THREAD

**Issue by jackwasey** [r-hub/pandoc-builders#4]
[Pandoc 2.6](https://github.com/jgm/pandoc/releases) is available, and in my particular use case, (for correctly formatting a manuscript using the 'rticles' package), I need at least pandoc 2.2.

I understand the workaround is to omit vignette building and checking, but wanted to flag this as a wish list item.

**Comment by gaborcsardi** [comment]
They have static builds for newer pandoc at https://github.com/jgm/pandoc/releases The goal of this repository was to create a working static build for pandoc 1.x.
